import { GoogleGenAI } from "@google/genai";

const apiKey = process.env.API_KEY || '';

// Safely initialize the client. 
// Note: In a real production build, ensure API_KEY is available.
// We handle missing keys gracefully in the UI.
const ai = apiKey ? new GoogleGenAI({ apiKey }) : null;

export const generateDashboardInsight = async (query: string): Promise<string> => {
  if (!ai) {
    // Simulate response if no key is present for demo purposes
    return new Promise(resolve => setTimeout(() => resolve("Connect your API Key to see real-time AI insights generated by SPARC."), 1000));
  }

  try {
    const model = 'gemini-2.5-flash';
    const response = await ai.models.generateContent({
      model,
      contents: query,
      config: {
        systemInstruction: "You are SPARC, a highly advanced AI dashboard assistant. Your interface is dark, minimal, and data-centric. Provide a brief, high-level executive summary of the user's hypothetical data query. Keep it under 50 words. Be professional, crisp, and insightful. Use numbers where appropriate.",
        temperature: 0.7,
      }
    });

    return response.text || "No insight generated.";
  } catch (error) {
    console.error("Gemini API Error:", error);
    return "Unable to generate insight at this moment. Please try again.";
  }
};